FROM public.ecr.aws/lambda/python:3.10

RUN yum install -y gcc git mesa-libGL
RUN pip install python-telegram-bot boto3 torch torchvision numpy opencv-python Pillow==9.5.0 --target "${LAMBDA_TASK_ROOT}"
RUN pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git --target "${LAMBDA_TASK_ROOT}"
